# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Rory Byrne
email: rory@syze.ai
description: >- # this means to ignore newlines until "baseurl:"
  Spiel.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rory.bio" # the base hostname & protocol for your site, e.g. http://example.com
author:
  name: Rory Byrne
twitter_username: ryrobyrne
github_username:  synek
aboutme: >-
  Hi, I'm Rory - software engineer transplant into neuroscience. Watch me learn.

# Build settings
collections_dir: collections

collections:
  learnings:
    output: true
    permalink: /learnings/:title/
  playbooks:
    output: true
    permalink: /playbooks/:path/

defaults:
  -
    scope:
      path: ''
      type: playbooks
    values:
      layout: playbook-detail

sass:
  sass_dir: css
  style:    expanded

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
